### ISSUE TITLE
Please update for Mantis 2.5

### ISSUE THREAD

**Issue by digitalsigi** [mantisbt-plugins/announce#7] opened 2017-06-19 13:57 UTC
Hi,
I would like to use this plugin with Mantis 2.5
Thx a lot

**Comment by dregad** [comment] 2017-06-19 14:00
Duplicate of #6

**Closed by dregad** 2017-06-19 14:00 UTC

**Comment by digitalsigi** [comment] 2017-06-19 14:09
OK, sorry for misunderstanding 2.1...
However, I am already on 2.5.0 and would like to install the plugin. Is there is no way?

**Comment by dregad** [comment] 2017-06-19 14:14
Unfortunately, not unless you or someone else is willing to provide a patch to update the plugin. 

I stopped using it several years ago, so I'm not sure how difficult it would be to adapt it to the MantisBT new UI. Don't have time to do it, but will gladly merge a pull request.

**Comment by digitalsigi** [comment] 2017-06-19 14:18
Got the point. 
Thx anyway.

**Comment by atrol** [comment] 2017-06-19 14:28
@digitalsigi you might want to use the embedded news functionality instead of this plugin.
You can try it by adding the following line to config_inc.php
```
$g_news_enabled = ON;
```
But keep in mind: This feature is deprecated and is expected to be moved to a plugin (maybe an updated version of the announce plugin).
I see no big risk in using it, as the current functionality will not be removed before a plugin is available.

**Comment by dregad** [comment] 2017-07-02 12:51
@digitalsigi Release 2.0.0 of the plugin is now available, with support for MantisBT 2.x
