### ISSUE TITLE
Blank page on manage plugin

### ISSUE THREAD

**Issue by anthony77120** [mantisbt-plugins/Announce#50] opened 2019-02-19 14:12 UTC
Hi,

I meet some difficulties to install the plug in "Announce"... does anyone can help me ?

Here are my steps :
- download the 2.4.1 version (.zip but it's the same with the tar.gz)
- unzip the directory "Announce- 2.4.1"
- rename the directory "Announce-2.4.1" by "Announce"
- Copy it to the mantis directory plugin
- Open mantis \ administration \ plugin (gérer les plugiciels)

=> the page is blank (except the menu), all my plugins (installed or not) are [masked)
=> if y modify the name of the directory "Announce" by "Announce-2.4.1" then the page works well but cannot find the plugin "Announce"

My Mantis Version is 2.5.1 (french)

**Comment by dregad** [comment] 2019-02-27 08:22
@anthony77120 unfortunately I am not able to reproduce the problem. 

The only out of the ordinary thing I get with Mantis 2.5.1 is a warning due to use of `each()` function (deprecated since PHP 7.2); this has been fixed in 2.9.0. I would advise that you upgrade your installation to the latest release (2.19.0 as of this writing) to benefit from the latest security patches, bug fixes and features.

Considering that a blank page is often caused by PHP errors, did you check your logs ?

**Comment by anthony77120** [comment] 2019-03-01 09:40
Ok thanks for your help, this is my opinon too....

I have tried many differents things in code or renamming folder/file but no way...so I will upgrade the Mantis Version and check after if it's good.

**Closed** 2019-03-01 09:40 UTC
Labels: can't reproduce
